### PR TITLE
Fix handling of no wells in WellStateFullyImplicitBlackoil.hpp

### LINKED ISSUE #731: Model 2 does not run
I get a floating point exception in `report()` in `WellStateFullyImplicitBlackoil.hpp` when I tried to run Model 2 with the current master.

### PR DESCRIPTION
**Pull request by blattms**
In that case we cannot call numPhases() on the wells as it produces
a floating point exception. As we do not use that information in this case
anyway, we simply use -1 instead to prevent the call.

Closes #731

### CODE REVIEW

File: opm/autodiff/WellStateFullyImplicitBlackoil.hpp [hunk 1]
```diff
@@ -195,7 +195,9 @@ namespace Opm
             data::Wells res = WellState::report();
 
             const int nw = this->numWells();
-            const int np = this->numPhases();
+            // If there are now wells numPhases throws a floating point
+            // exception.
+            const int np = nw ? this->numPhases() : -1;
```
Comment (atgeirr) [inline opm/autodiff/WellStateFullyImplicitBlackoil.hpp]: A more elegant fix: move the np variable inside the for-loop, since it is only used there. (Won't require, tell me if you want to do that or keep this as currently proposed.)

Comment (blattms) [inline opm/autodiff/WellStateFullyImplicitBlackoil.hpp]: I would prefer to leave at as is. Only one if branch and one division
in this case.

Comment (atgeirr) [inline opm/autodiff/WellStateFullyImplicitBlackoil.hpp]: Ok.

(But I don't see why we'd need an if, that was the point of putting it in the loop where it would unconditionally be ok?)
