### PR TITLE
Fix parallel output

### LINKED ISSUE #830: Logging does not works as expected for parallel runs.
As the logger is not aware of parallelism (and most parts of the rest of the code are neither) there are several places where similar stuff is logged from multiple places. In most of the place we already output on the root process (rank 0), but there are still issue like:
- non-root processes create an additional *.PRT file in the current director when output_dir is set. If it is not set most probably multiple processes will still write to this file.
- some messages about events that only appear on non-root processes are never logged
- ZOLTAN logs to std::cout

### PR DESCRIPTION
**Pull request by blattms**
Before this PR logging was done  regardless whether it was a sequential or a parallel run. Leading to  multiple processes logging simultaneously to the same file and causing message loss.

This PR fixes this in the following ways:
- If possible log only on one process.That is the case if all processes have the same information.
- Gather all messages about well switching on a root process and log there. (This might cost us some runtime, though)
- To prevent losses and surprises (if the above does either not suffice or we missed some parts): Each process now logs to its own file and after the simulation is finished the log of non-root processes are 
append to the default log files.

Closes #830 in most parts. One exception is the logging within OPM_THROW which will still happen on all processes.

### CODE REVIEW

**Comment by blattms** [comment]
Also closes  #572.

**Comment by atgeirr** [comment]
I am very happy to see this @blattms! It is big however, and will take some time to review properly, I will probably not have time before next week. Perhaps @dr-robertk can also help looking at it?

**Comment by GitPaean** [comment]
Unknown reason causes one of the test failed, 
```
14: Test command: /home/kaib/software/petsc-3.7.3/arch-linux2-c-debug/bin/mpiexec "-np" "1" "/home/kaib/OPM-devel-2/debug/opm-simulators-build/bin/test_multisegmentwells"
14: Test timeout computed to be: 1500
14: Running 2 test cases...
14: unknown location(0): fatal error in "testOperators": unknown type
14: unknown location(0): fatal error in "testStructure": unknown type
14: 
14: *** 2 failures detected in test suite "MultisegmentWellsTest"
```
which got problem in line 121 in `test_multisegmentwells.cpp`

```ms_wells.reset(new Opm::MultisegmentWells(wells, wells_ecl, current_timestep));. ```

Not sure directly related to this PR, will investigate more.

File: opm/autodiff/FlowMain.hpp [hunk 1]
```diff
@@ -109,6 +111,101 @@ namespace Opm
     {
         boost::filesystem::path simulationCaseName( const std::string& casename );
         int64_t convertMessageType(const Message::type& mtype);
+
+        namespace fs = boost::filesystem;
```
Comment (atgeirr) [inline opm/autodiff/FlowMain.hpp]: I'd like the ParallelFileMerger class to be moved to a separate file, since it is a separate concept from FlowMain.

File: opm/autodiff/FlowMain.hpp [hunk 2]
```diff
@@ -109,6 +111,101 @@ namespace Opm
...
+    /// Non-root processes will do that to seperate files
+    /// <basename>.<rank>.<extension. This functor will append those file
+    /// to usual ones and delete the other files.
+    class ParallelFileMerger
+    {
+    public:
+        /// \brief Constructor
+        /// \param output_dir The output directory to use for reading/Writing.
+        /// \param deckanme The name of the deck.
+        ParallelFileMerger(fs::path output_dir,
```
Comment (atgeirr) [inline opm/autodiff/FlowMain.hpp]: Why not a const reference?

File: opm/autodiff/FlowMain.hpp [hunk 3]
```diff
@@ -109,6 +111,101 @@ namespace Opm
...
+        void operator()(const fs::path& file)
+        {
+            const static boost::regex regex(".+\\.(\\d+)\\..+");
+            boost::smatch matches;
+            std::string filename = file.filename().native();
+
+            if ( boost::regex_match(filename, matches, regex) )
+            {
+                std::string rank = boost::regex_replace(filename, regex, "\\1");
+
```
Comment (atgeirr) [inline opm/autodiff/FlowMain.hpp]: Remove extra blank line.

File: opm/autodiff/FlowMain.hpp [hunk 4]
```diff
@@ -109,6 +111,101 @@ namespace Opm
...
+    private:
+        /// \brief Append contents of a file to a stream
+        /// \brief of The output stream to use.
+        /// \brief file The file whose content to append.
+        /// \brief rank The rank that wrote the file.
+        void appendFile(fs::ofstream& of, const fs::path& file, const std::string& rank)
+        {
+            if( fs::file_size(file) )
+            {
+                std::cerr<<"WARNING: There has been logging out by non-root process "
```
Comment (atgeirr) [inline opm/autodiff/FlowMain.hpp]: Add spaces around binary ops such as `<<`.

File: opm/autodiff/FlowMain.hpp [hunk 5]
```diff
@@ -369,36 +482,75 @@ namespace Opm
...
             streamLog->setMessageFormatter(std::make_shared<SimpleMessageFormatter>(true));
             // Read parameters.
-            OpmLog::debug("\n---------------    Reading parameters     ---------------\n");
+            if ( output_cout_ )
+            {
+                OpmLog::debug("\n---------------    Reading parameters     ---------------\n");
+            }
         }
 
+        void mergeParallelLogFiles()
```
Comment (atgeirr) [inline opm/autodiff/FlowMain.hpp]: Add more blank lines to keep whitespace consistent and beautiful throughout the file :-)

File: opm/autodiff/FlowMain.hpp [hunk 6]
```diff
@@ -618,6 +775,9 @@ namespace Opm
         //    OpmLog singleton.
         void extractMessages()
         {
+            if ( !output_cout_ )
```
Comment (atgeirr) [inline opm/autodiff/FlowMain.hpp]: Please add braces.

File: opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp [hunk 7]
```diff
@@ -636,7 +650,8 @@ namespace Opm
     {
         const RestartConfig& restartConfig = eclipseState_->getRestartConfig();
         const int reportStepNum = timer.reportStepNum();
-        std::vector<data::CellData> cellData = detail::getCellData( phaseUsage_, physicalModel, restartConfig, reportStepNum );
+        std::vector<data::CellData> cellData = detail::getCellData( phaseUsage_, physicalModel, restartConfig, reportStepNum,
+                                                                    output_ && parallelOutput_->isIORank() );
```
Comment (atgeirr) [inline opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp]: This is an important change I think. I guess all data will be gathered on rank 0 and written only from there? Will not this result in incomplete data being stored, since we should extract data from all ranks, not just from rank 0?

File: opm/simulators/WellSwitchingLogger.cpp [hunk 8]
```diff
@@ -0,0 +1,206 @@
...
+    {
+        unpackDataAndLog(recv_buffer, displ);
+    }
+#endif
+}
+
+
+WellSwitchingLogger::~WellSwitchingLogger()
+{
+    gatherDataAndLog();
```
Comment (atgeirr) [inline opm/simulators/WellSwitchingLogger.cpp]: I realize this is not the first time this pattern (do stuff in the destructor) is used in OPM, but I have become a bit wary of it, as it goes against one of the fundamental guidelines in C++: never throw in a destructor. I am not going to require this to change here, but we should think about it and see if there is another way to do this.

File: opm/simulators/WellSwitchingLogger.cpp [hunk 9]
```diff
@@ -0,0 +1,206 @@
...
+    {
+        int length = switchEntry.first.size() +1;  //we write an additional \0
+        well_name_length.push_back(length);
+    }
+
+    // compute the message size
+    int message_size = 0;
+    int increment = 0;
+    // number of switches
+    MPI_Pack_size(1, MPI_INT, MPI_COMM_WORLD, &message_size);
```
Comment (atgeirr) [inline opm/simulators/WellSwitchingLogger.cpp]: It looks like `&message_size` should be `&increment`.

File: opm/simulators/WellSwitchingLogger.cpp [hunk 10]
```diff
@@ -0,0 +1,206 @@
...
+    message_size += increment;
+    // const char* length include delimiter for each switch
+    MPI_Pack_size(switchMap_.size(), MPI_INT, MPI_COMM_WORLD, &increment);
+    message_size += increment;
+    // for each well the name + two controls in one write
+    auto length = well_name_length.begin();
```
Comment (atgeirr) [inline opm/simulators/WellSwitchingLogger.cpp]: Confusing name, calling it length_iter or similar would be better.

File: opm/simulators/WellSwitchingLogger.cpp [hunk 11]
```diff
@@ -0,0 +1,206 @@
...
+
+    for(const auto& switchEntry : switchMap_)
```
Comment (atgeirr) [inline opm/simulators/WellSwitchingLogger.cpp]: Since switchEntry is not used in this loop, it could be over well_name_length instead, simplifying a little bit.

File: opm/simulators/WellSwitchingLogger.cpp [hunk 12]
```diff
@@ -0,0 +1,206 @@
...
+}
+
+void WellSwitchingLogger::unpackDataAndLog(std::vector<char>& recv_buffer,
+                                           const std::vector<int>& displ)
+{
+    for(int p=1; p < cc_.size(); ++p)
+    {
+        int offset = displ[p];
+        int no_switches = 0;
+        MPI_Unpack(recv_buffer.data(), recv_buffer.size(), &offset,
```
Comment (atgeirr) [inline opm/simulators/WellSwitchingLogger.cpp]: There is no error checking here, it would be good to verify that the MPI ops were successful before accessing the results. However, throwing should not be done as that could go down the rabbit hole (being called from a destructor).

Also: I assume offset get automatically bumped by each call to MPI_Unpack()?

File: opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp (hunk 7 above)
Comment (blattms) [inline opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp]: Without a  name the bool parameter is a bit misleading.  It only switches the logging on or of. I made  a change to make this more clear. The cellData is always populated with the local values.

File: opm/simulators/WellSwitchingLogger.cpp (hunk 9 above)
Comment (blattms) [inline opm/simulators/WellSwitchingLogger.cpp]: Fortunately the following statement is `message_size +=  increment` and translates to message_size += 0`. Changing anyway.

File: opm/simulators/WellSwitchingLogger.cpp (hunk 10 above)
Comment (blattms) [inline opm/simulators/WellSwitchingLogger.cpp]: I do not like this kind of naming (from before auto times). But to make you happy....

File: opm/simulators/WellSwitchingLogger.cpp (hunk 11 above)
Comment (blattms) [inline opm/simulators/WellSwitchingLogger.cpp]: I might not understand your comment but I think it is wrong as we populate well_name_length here using push_back

File: opm/simulators/WellSwitchingLogger.cpp (hunk 12 above)
Comment (blattms) [inline opm/simulators/WellSwitchingLogger.cpp]: Well MPI error checking is a nightmare:
```
int res =MPI_Unpack();
if ( res != MPI_SUCCESS) {
   std::vector<char> error_string(BUFSIZ);
   int length_of_error_string, error_class;
   MPI_Error_class(error_code, &error_class);
   MPI_Error_string(error_class, error_string.data(), &length_of_error_string);
   error_string[length_of_error_string] = '\000';
   cout<<my_rank<<" "<<error_string.data()<<endl;
   MPI_Error_string(error_code, error_string, &length_of_error_string);
   error_string[length_of_error_string] = '\000';
   cout<<my_rank<<" "<< error_string.data()<<endl;
   MPI_Abort
}
The default  error handling is to abort the program anyway. http://beige.ucs.indiana.edu/I590/node85.html. Therefore in 99% of the cases it is a waste of time. For debugging one can change the error handler to a custon one that prints the error and throws. Thus we get the message and can attach with a debugger.

Yes offset is inreased automagically.

File: opm/simulators/WellSwitchingLogger.cpp (hunk 8 above)
Comment (blattms) [inline opm/simulators/WellSwitchingLogger.cpp]: Well for the default settings and no programming errors it does not throw.

**Comment by blattms** [comment]
@GitPaen Seems like the test needs to initialize MPI. I will cook up  a patch.

File: opm/autodiff/FlowMain.hpp (hunk 5 above)
Comment (atgeirr) [inline opm/autodiff/FlowMain.hpp]: OK here is what I would like: to have the amount of blank lines reflect how distant the things separated by the lines are. Having a single blank line between every non-blank line (as an extreme case example) makes no sense, since it gives no contrast. It is that contrast that gives an intuitive grasp of the structure of the code I want. That boils down to the following basic rules of thumb:
 - never more than a single blank line inside a function,
 - usually more than a single blank line between function definitions (and I think 4-5 is nice here).

It's a nitpick but one of my favorite ones...

**Comment by blattms** [comment]
@GitPaean Please try again. Should be fixed.

File: opm/simulators/WellSwitchingLogger.cpp (hunk 10 above)
Comment (atgeirr) [inline opm/simulators/WellSwitchingLogger.cpp]: I think it is an important distinction: is `++length` increasing a quantity or moving an iterator, for example? Pointers and references are different since they still semantically represent just a single object, but an iterator is not and therefore needs a name that says so.

File: opm/simulators/WellSwitchingLogger.cpp (hunk 12 above)
Comment (atgeirr) [inline opm/simulators/WellSwitchingLogger.cpp]: > MPI error checking is a nightmare

I can see that... Forget I asked!

File: opm/simulators/WellSwitchingLogger.cpp [hunk 13]
```diff
@@ -0,0 +1,205 @@
...
+    int increment = 0;
+    // number of switches
+    MPI_Pack_size(1, MPI_INT, MPI_COMM_WORLD, &message_size);
+    // const char* length include delimiter for each switch
+    MPI_Pack_size(switchMap_.size(), MPI_INT, MPI_COMM_WORLD, &increment);
+    message_size += increment;
+    // for each well the name + two controls in one write
+    auto length_iter = well_name_lengths.begin();
+
+    for(const auto& switchEntry : switchMap_)
```
Comment (atgeirr) [inline opm/simulators/WellSwitchingLogger.cpp]: Comment was lost I think: this loop does not use switchEntry (should generate a warning), and should loop over well_name_lengths instead. The loop above that creates well_name_lengths should still loop over switchEntry.

**Comment by GitPaean** [comment]
> @GitPaean Please try again. Should be fixed.

The multi-segment well test works now.

**Comment by blattms** [comment]
> Comment was lost I think: this loop does not use switchEntry (should generate a warning), and should loop over well_name_lengths instead. The loop above that creates well_name_lengths should still loop over switchEntry.

I read comment and looked at the wrong lines of code. Now I got it and
fixed it.

**Comment by atgeirr** [comment]
I think this looks good now, will merge when green. Thanks a lot for the effort!

**Comment by akva2** [comment]
when doing parallel the only green that counts is jenkins.

**Comment by atgeirr** [comment]
> when doing parallel the only green that counts is jenkins.

Ok, will start a Jenkins job, too. Did you notice anything wrong by the way?

**Comment by atgeirr** [comment]
jenkins run norne polymer please

**Comment by blattms** [comment]
See #853 for the fix of the fix.
