### PR TITLE
Fix using local active cells for writing eclipse files in parallel.

### LINKED ISSUE #892: Parallel runs with Norne hang because of exception in output code.
There is an exception thrown when writing the first time step:

```
After loadbalancing process 1 has 16801 cells.
After loadbalancing process 0 has 30146 cells.
================ Starting main simulation loop ===============
Error: Program threw an exception: Input argument does not correspond to an active cell
```
backtrace is:
```
#0  0x00007ffff450edbd in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000154831d in Opm::EclipseGrid::activeIndex (this=0xf3b2278,
    globalIndex=2003)
    at /home/mblatt/DUNE-test/opm-parser/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp:234
#2  0x0000000001312699 in Opm::(anonymous namespace)::crate<(Opm::data::Rates::opt)1, true> (args=...)
    at /home/mblatt/DUNE-test/opm-output/opm/output/eclipse/Summary.cpp:217
#3  0x0000000001314995 in std::_Function_handler<Opm::(anonymous namespace)::quantity(const Opm::(anonymous namespace)::fn_args&), Opm::(anonymous namespace)::quantity (*)(const Opm::(anonymous namespac\
e)::fn_args&)>::_M_invoke(const std::_Any_data &, const Opm::(anonymous namespace)::fn_args &) (__functor=...,
    __args#0=...) at /usr/include/c++/4.9/functional:2025
#4  0x0000000001314443 in std::function<Opm::(anonymous namespace)::quantity(const Opm::(anonymous namespace)::fn_args&)>::operator()(const Opm::(anonymous namespace)::fn_args &) const (this=0xc8bd2e8, __args#0=...)
    at /usr/include/c++/4.9/functional:2439
#5  0x000000000131113b in Opm::out::Summary::add_timestep (this=0xf3b2398,
    report_step=0, secs_elapsed=0, grid=..., es=..., regionCache=...,
    wells=..., state=...)
    at /home/mblatt/DUNE-test/opm-output/opm/output/eclipse/Summary.cpp:751
#6  0x000000000130a4ca in Opm::EclipseWriter::writeTimeStep (this=0x2d02950,
    report_step=0, isSubstep=false, secs_elapsed=0, cells=..., wells=...,
    write_float=true)
    at /home/mblatt/DUNE-test/opm-output/opm/output/eclipse/EclipseWriter.cpp:811
#7  0x00000000011b088f in Opm::BlackoilOutputWriter::writeTimeStepSerial (
    this=0x9820200, timer=..., state=..., wellState=..., simProps=...,
    substep=false)
    this=0x9820200, timer=..., state=..., wellState=..., simProps=...,
    substep=false)
    at /home/mblatt/DUNE-test/opm-simulators/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp:38\
3
#8  0x00000000011b059c in Opm::BlackoilOutputWriter::writeTimeStepWithCellProperties (this=0x9820200, timer=..., localState=..., localWellState=...,
    cellData=..., substep=false)
    at /home/mblatt/DUNE-test/opm-simulators/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp:350
#9  0x00000000011b0235 in Opm::BlackoilOutputWriter::writeTimeStepWithoutCellProperties (this=0x98202\
00, timer=..., localState=..., localWellState=...,
    substep=false)
    at /home/mblatt/DUNE-test/opm-simulators/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp:303
#10 0x0000000000f39270 in Opm::SimulatorBase<Opm::SimulatorFullyImplicitBlackoil<Dune::CpGrid> >::run (this=0x7e9c210, timer=..., state=...)
    at /home/mblatt/DUNE-test/opm-simulators/opm/autodiff/SimulatorBase_impl.hpp:190

#11 0x0000000000f18f82 in Opm::FlowMainBase<Opm::FlowMain<Dune::CpGrid, Opm::SimulatorFullyImplicitBlackoil<Dune::CpGrid> >, Dune::CpGrid, Opm::SimulatorFullyImplicitBlackoil<Dune::CpGrid> >::runSimulator (this=0x7fffffffded0)
    at /home/mblatt/DUNE-test/opm-simulators/opm/autodiff/FlowMain.hpp:836
#12 0x0000000000efe96a in Opm::FlowMainBase<Opm::FlowMain<Dune::CpGrid, Opm::SimulatorFullyImplicitBlackoil<Dune::CpGrid> >, Dune::CpGrid, Opm::SimulatorFullyImplicitBlackoil<Dune::CpGrid> >::execute (this=0x7fffffffded0, argc=2,
    argv=0x7fffffffe148)
    at /home/mblatt/DUNE-test/opm-simulators/opm/autodiff/FlowMain.hpp:157
#13 0x0000000000ecdab1 in main (argc=2, argv=0x7fffffffe148)
    at /home/mblatt/DUNE-test/opm-simulators/examples/flow_mpi.cpp:41
```

Not sure what goes wrong, yet.  The global index found not to be active is `2003`.

### PR DESCRIPTION
**Pull request by blattms**
Previously, the eclipseGrid used by EclipseWriter was constructed from
the one in the EclipseState with the current CpGrid. Unfortunately the
latter was the distributed version resembling only the local part that
the processor works on. Therefore the information about the active cells
was wrong when writing results (which raised an exception in the writer).

With this commit we construct the EclipseWriter before distributing the grid
and use this writer later on in the OutputWriter.

Closes #892

### CODE REVIEW

**Comment by blattms** [comment]
jenkins run norne polymer please

**Comment by atgeirr** [comment]
I notice the following comment in FlowMain::setupOutputWriter():
```
// create output writer after grid is distributed, otherwise the parallel output
// won't work correctly since we need to create a mapping from the distributed to
// the global view
```
This confuses me a bit: is this still true? Is it so that the EclipseWriter (on the output rank) needs the global grid, but other parts need the distributed grid? The implementation looks a bit brittle to me, passing the unique_ptr by reference etc. Could we not explicitly retain and pass the global grid instead (at least on the output rank)?

**Comment by joakim-hove** [comment]
> Is it so that the EclipseWriter (on the output rank) needs the global grid, but other parts need the distributed grid? 

Hopefully I am not muddying the waters further here - but anyway: The output writer has *no notion of parallell simulations*. The output functionality should be called *once*, and that call should pass *all* the data required for output. I.e. as seen from the output it is the responsability of the simulator to abstract away all notions of parallell.

**Comment by atgeirr** [comment]
> The output writer has no notion of parallell simulations.

That is a good clarification, and not muddying the waters. It is also consistent with the general approach, which is that most of the code is totally unaware.

**Comment by blattms** [comment]
@atgeirr Yes it is still true. The term output writer is not very precise though. The ParallelDebugOutput needs both views (local and global) on the master. These are only available once the grid is distributed.

You are right with regard to the unique_ptr. I will improve that.

**Comment by blattms** [comment]
Please hold off merging. I am currently getting:
'Error: Program threw an exception: Input vector must have full size.

I will run some tests with other modules updated.

**Comment by blattms** [comment]
Well, the new problem appears at [EclipseWriter.cpp:782](/OPM/opm-output/blob/254e93467699284639ffeb03d737328ceb4d5215/opm/output/eclipse/EclipseWriter.cpp#L782). Somehow the `prop.second.data` has only the local number of active cells.

**Comment by blattms** [comment]
What is this new `data::cellData`? It only contains local data.

**Comment by blattms** [comment]
And the real origin is that the restart data gets initialized from a local EclipseGrid [here](/OPM/opm-simulators/blob/736585e85bf742b25d651023112c1e36a4bb8938/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp#L777-L787). Is there a reason why we cannot postpone this until `SimulatorFullyImplicitBlackoilOutput::writeTimeStepSerial?

Maybe we should open a new bug and PR for fixing the restart stuff?

**Comment by blattms** [comment]
`data::cellData` currently contains local data for the restart stuff and global data from the simulator run.

**Comment by akva2** [comment]
heads up; i'm in the process of finalizing an initial version for the gather of well states for restart purposes.

**Comment by akva2** [comment]
and yes, i noticed all the things you point to looking into the scatter (which i gave up on, there's too much fundamental breakage for parallel restart still).

**Comment by akva2** [comment]
.. and then i realized that my syncing data won't help much. output for wells is tied to the well manager state, and the well manager is only instanced for the local wells, so even though the well state is now filled with the global data, it won't be written. somebody pass the parmesan please.

**Comment by blattms** [comment]
@joakim-hove Can you confirm that `BlackoilWriter::eclipseState_` is there solely used for the restart functionality?

**Comment by blattms** [comment]
I posed the wrong question. The real question what is the `physicalModel` is for? At the problematic scope it is used to create data for writing some restart stuff. Unfortunately, physicalModel is only local and that causes the problems currently.

**Comment by akva2** [comment]
@blattms see top commit in https://github.com/akva2/opm-simulators/commits/parallel_io_tests for where i get stuck (yes, i was a bit fast, it's the physicalModel.schedule () which bites). i have no attempts at doing pretty code, and it is certainly not meant for inclusion as-is.

**Comment by joakim-hove** [comment]
> I posed the wrong question. The real question what is the physicalModel is for? At the problematic scope it is used to create data for writing some restart stuff. Unfortunately, physicalModel is only local and that causes the problems currently.

I guess @atgeirr or @babrodtk are more qualified to answer this question; but the code in question is there to output *auxillary* state information to restart file. This is information which is not needed for restart (like e.g. pressure and saturations) - only diagnostic information requested by the user.

**Comment by blattms** [comment]
Well, I kind of long for the good old times, where only correct well curves were of interest.

**Comment by blattms** [comment]
Anyway I will not add any more commits on this PR it fixes the issue described. Unfortunately, we running into the next exception now. Merge at your disgression

**Comment by blattms** [comment]
Old status restored. Instead of the exception in parallel runs one now gets a warning like
"Warning: Output of restart/summary config not supported in parallel. Requested keywords were WIP OIPL OIPG OIP GIPG GIPL GIP BASIC KRG KRO KRW"

**Comment by blattms** [comment]
jenkins run norne please

File: opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp [hunk 1]
```diff
@@ -774,16 +785,56 @@ namespace Opm
...
+
+                for (auto& keyValue : rstKeywords)
+                {
+                        str << keyValue.first << " ";
+                        ++ no_kw;
+                }
 
+                if ( no_kw )
+                {
+                    Opm::OpmLog::warning("Unhandled ouput request", str.str());
```
Comment (atgeirr) [inline opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp]: Typo, "ouput".
