### PR TITLE
Don't Output INFOSTEP File by Default

### LINKED ISSUE #3710: Unexpected file written out by default
Flow by default prints out a file with suffix INFOSTEP. This file seems to be only for developers of numerical optimizations that want additional information. For users the file is noise, and scripts to clean up folders after simulations may need to be aware of it. There are at least three options that could remedy this, and I believe all of them is better:
* make the output of the file optional, for instance through a command line switch
* add the extra time step information to the LOG and/or PRT file
* send the information to the DBG file, for instance starting each line with the string INFOSTEP to make it trivial to extract

### PR DESCRIPTION
**Pull request by bska**
This PR introduces a new helper class,
```
ConvergenceOutputConfiguration
```
which parses comma separated option strings into a runtime configuration object for whether to output additional convergence information and, if so, what information to output.

Supported option string values are

  * `"none"`&mdash;Dont want any additional convergence output.
  * `"steps"`&mdash;Want additional convergence output pertaining to the converged solution at the end of each timestep.
  * `"iteration"`&mdash;Want additional convergence output pertaining to each non-linar ieration in each timestep.

Option value `"none"` overrides all other options.  In other words, if the user requests `"none"`, then there will be no additional convergence output, even if there are other options in the option string.

We add a new option, `ExtraConvergenceOutput` (command line option `--extra-convergence-output`), which takes a string argument expected to be a comma separated combination of these options.  The default value is `"none"`.  Finally, make the `INFOSTEP` file output conditional on the user supplying `"steps"` as an argument to the new option.

Resolves #3710.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Here's an excerpt from the `.INFOITER` file from a local run of the [`DROGON_PRED`](https://github.com/OPM/opm-tests/blob/2043a33f27c2872006c46f948e95021a7e1c667a/drogon/model/DROGON_PRED.DATA) case to give a feel for the kind of information contained in the file.

---

```
 ReportStep    TimeStep        Time   Iteration      MB_Oil     CNV_Oil    MB_Water   CNV_Water      MB_Gas     CNV_Gas  WellStatus
         82           0  9.1200e+02           0  2.3284e-05  4.5422e-02  1.1767e-05  2.5912e+01  9.7662e-06  7.4694e-02        CONV
         82           0  9.1200e+02           1  2.9654e-07  3.8767e+00  2.1806e-07  4.1394e+00  5.2375e-08  2.9183e+01        CONV
         82           0  9.1200e+02           2  2.2179e-07  6.8047e-01  3.0610e-07  1.1331e+00  9.1907e-08  3.8215e+00        CONV
         82           0  9.1200e+02           3  7.9218e-08  2.1570e-01  1.0786e-07  9.9523e-01  3.6969e-08  2.5988e-01        CONV
         82           0  9.1200e+02           4  1.0330e-09  1.3516e+00  3.9736e-09  7.8332e-02  1.6815e-09  4.7527e-01        CONV
         82           0  9.1200e+02           5  2.0293e-10  8.8220e-03  6.3183e-10  8.3824e+00  2.2348e-10  2.3677e-02        CONV
         82           0  9.1200e+02           6  3.4981e-11  3.0447e-03  7.7930e-11  7.1824e-01  5.5410e-11  1.0453e-03        CONV
         82           0  9.1200e+02           7  2.5736e-12  1.2814e-03  2.4878e-12  6.9697e-02  3.7422e-11  5.9990e-04        CONV
         82           0  9.1200e+02           8  9.4203e-13  1.5313e-04  1.7662e-12  6.2323e-03  2.7139e-12  5.2559e-05        CONV
[...]
        101           0  1.4610e+03           1  2.4697e-04  7.0125e+00  1.0699e-06  9.3247e+00  1.0367e-04  4.1111e+01        FAIL
        101           0  1.4610e+03           2  2.3446e-04  7.6941e+00  1.1321e-06  4.3870e+00  9.9849e-05  3.2322e+00        CONV
        101           0  1.4610e+03           3  2.4519e-04  2.4764e+00  1.1091e-07  1.1195e+00  1.0521e-04  1.8365e+01        FAIL
        101           0  1.4610e+03           4  2.2569e-04  5.2145e+00  8.3692e-06  2.0409e-01  1.0160e-04  2.1750e+00        CONV
        101           0  1.4610e+03           5  3.9522e-06  1.4566e+00  4.4403e-07  1.1981e+00  9.6223e-06  1.9711e+01        CONV
        101           0  1.4610e+03           6  8.3787e-06  8.9540e+00  5.0083e-07  5.7035e-01  3.5820e-06  3.2819e+00        CONV
        101           0  1.4610e+03           7  2.2669e-06  1.7800e+00  1.8097e-07  7.8105e-02  9.4668e-07  2.6049e+00        CONV
        101           0  1.4610e+03           8  5.0458e-07  3.3687e-01  1.1915e-07  8.3545e-03  7.3566e-07  3.1211e+00        CONV
        101           0  1.4610e+03           9  2.4234e-07  4.6142e-02  1.0972e-07  9.1612e-04  3.8631e-07  6.6698e-01        CONV
        101           0  1.4610e+03          10  8.8876e-07  1.2618e-02  2.2543e-08  1.7938e-04  3.8122e-07  9.8301e-02        CONV
[...]
        113           0  1.8260e+03           0  3.9049e-04  3.4754e+00  1.6306e-04  2.5447e+00  1.9202e-04  1.5925e+00        CONV
        113           0  1.8260e+03           1  2.5609e-04  1.8427e+01  1.1756e-04  3.4471e+01  7.9326e-05  2.6651e+02        FAIL
        113           0  1.8260e+03           2  1.6074e-04  3.0898e+02  2.8540e-05  1.7710e+01  7.1727e-05  1.0152e+02        FAIL
        113           0  1.8260e+03           3  2.7808e-05  5.5706e+00  1.0439e-05  1.6193e+01  1.3878e-05  1.9967e+01        FAIL
        113           0  1.8260e+03           4  2.0310e-05  2.1713e+00  1.1343e-05  4.2916e+00  9.1809e-06  1.7611e+01        FAIL
        113           0  1.8260e+03           5  1.2393e-05  6.9098e+00  7.1964e-06  9.3729e-01  9.0662e-07  6.3514e+00        FAIL
        113           0  1.8260e+03           6  3.8059e-06  2.1091e+00  4.5883e-07  3.1448e-01  1.3182e-06  1.3689e+01        FAIL
        113           0  1.8260e+03           7  1.0520e-07  6.2311e-01  2.2739e-07  2.2595e-01  1.4728e-07  3.4982e+00        FAIL
        113           0  1.8260e+03           8  3.6760e-09  1.0626e-01  1.1834e-08  5.7336e-02  2.1837e-08  6.9609e-01        FAIL
        113           0  1.8260e+03           9  1.4687e-08  1.8172e-02  5.5110e-08  2.2440e-03  7.8427e-09  8.4317e-03        FAIL
        113           0  1.8260e+03          10  1.8306e-09  3.1723e-05  5.4198e-09  6.2984e-06  1.3070e-09  1.9392e-05        FAIL
        113           0  1.8260e+03          11  3.8017e-12  7.4210e-09  3.4998e-12  1.7551e-08  1.0524e-12  5.5179e-09        FAIL
        113           0  1.8260e+03          12  3.7820e-15  3.5240e-10  2.6918e-15  2.6820e-08  2.5483e-15  1.9588e-09        FAIL
        113           0  1.8260e+03          13  3.2360e-16  2.8521e-10  6.4618e-16  1.2857e-08  1.8377e-16  9.8643e-10        FAIL
        113           0  1.8260e+03          14  2.5688e-16  2.8569e-10  6.0128e-16  2.6820e-08  1.4191e-16  1.1094e-09        FAIL
        113           0  1.8260e+03          15  1.9524e-16  3.4905e-10  5.1244e-16  2.6820e-08  1.1677e-16  1.1094e-09        FAIL
        113           0  1.8260e+03          16  1.6093e-16  3.4858e-10  4.7598e-16  1.2601e-08  8.9227e-17  9.8642e-10        FAIL
        113           0  1.8260e+03          17  1.0243e-16  2.8600e-10  4.0966e-16  2.6820e-08  6.6551e-17  8.6481e-10        FAIL
        113           0  1.8260e+03          18  6.4405e-17  3.4864e-10  3.8223e-16  1.2993e-08  4.2039e-17  9.8642e-10        FAIL
        113           0  1.8260e+03          19  5.5481e-17  2.8647e-10  3.2872e-16  1.2601e-08  3.5436e-17  8.6481e-10        FAIL
        113           0  1.8260e+03          20  4.8745e-17  2.8681e-10  3.0035e-16  1.2601e-08  3.0282e-17  9.8642e-10        FAIL
[...]
        113           0  1.8260e+03          20  2.2724e-18  5.2625e-11  1.4357e-18  1.7888e-09  1.8776e-18  8.4192e-11        FAIL
        113           0  1.8260e+03           0  5.2653e-06  1.2490e-01  8.6797e-06  9.1448e-02  2.9507e-06  5.7228e-02        FAIL
        113           0  1.8260e+03           1  8.7525e-06  9.3325e-02  2.8342e-06  1.0308e-01  3.8617e-06  1.7602e-01        CONV
        113           0  1.8260e+03           2  2.3667e-08  1.2853e+00  8.1819e-09  6.4745e-01  6.3189e-08  4.6300e-01        CONV
        113           0  1.8260e+03           3  4.8937e-09  1.8799e-02  3.8632e-10  3.6341e-02  4.9590e-09  5.1495e-03        CONV
        113           0  1.8260e+03           4  2.0833e-11  1.9696e-02  1.4980e-10  8.5118e-03  8.1549e-11  7.2504e-03        CONV
        113           0  1.8260e+03           5  3.2286e-11  5.3966e-05  5.9882e-11  6.5047e-05  2.2947e-11  1.2951e-05        CONV
        113           1  1.8276e+03           0  2.8208e-05  1.2664e-01  1.1830e-05  7.7499e-02  1.4066e-05  4.3010e-02        CONV
        113           1  1.8276e+03           1  1.4922e-07  1.7558e-01  5.6622e-08  2.1161e-02  3.2399e-07  6.8541e-02        CONV
        113           1  1.8276e+03           2  2.7998e-09  5.6454e-03  3.7268e-09  3.6810e-04  3.1496e-09  1.7606e-01        CONV
        113           1  1.8276e+03           3  5.5404e-11  6.1535e-05  1.3693e-09  1.0380e-05  1.1006e-09  8.1681e-04        CONV
        113           2  1.8309e+03           0  8.2516e-05  3.2507e-01  3.4014e-05  1.6135e-01  4.1262e-05  1.0169e-01        CONV
        113           2  1.8309e+03           1  4.0997e-07  3.3706e-01  1.7573e-07  7.6731e-01  1.3122e-06  7.5980e+00        CONV
        113           2  1.8309e+03           2  3.6539e-07  7.6224e-02  2.1905e-07  8.8526e-03  1.2124e-07  3.1422e-01        CONV
        113           2  1.8309e+03           3  1.5593e-08  1.1497e-02  1.9057e-08  6.5946e-04  4.2951e-09  5.7465e-02        CONV
        113           2  1.8309e+03           4  4.8145e-09  4.2523e-04  5.6881e-09  6.1615e-05  4.4490e-09  4.7093e-03        CONV
        113           3  1.8406e+03           0  2.0258e-04  3.1557e-01  8.0249e-05  1.8944e-01  1.0162e-04  1.0308e-01        CONV
        113           3  1.8406e+03           1  1.2758e-05  7.6781e-01  8.3830e-06  7.6012e-01  9.8801e-06  1.7799e+01        CONV
        113           3  1.8406e+03           2  2.5889e-07  2.2291e-01  3.4152e-07  8.4219e-01  6.8862e-07  1.1085e+00        CONV
        113           3  1.8406e+03           3  2.7877e-07  1.3765e-02  2.8271e-07  1.2804e-02  1.3694e-07  1.4943e-01        CONV
        113           3  1.8406e+03           4  4.0608e-08  1.7254e-03  6.3353e-08  1.0998e-04  3.0579e-08  6.3483e-03        CONV
[,,,]
        121           0  2.5560e+03           0  4.4604e-06  1.1096e-03  1.6743e-06  1.8258e-03  2.8787e-06  1.7979e-03        CONV
        121           0  2.5560e+03           1  2.3385e-10  1.2480e-05  2.5796e-09  2.7216e-05  5.7186e-10  5.8535e-06        CONV
        121           0  2.5560e+03           2  7.5900e-14  1.0572e-09  4.2859e-13  2.2994e-07  4.6956e-13  8.8884e-10        CONV
```

**Comment by bska** [comment]
jenkins build this please

**Comment by alfbr** [comment]
I am very happy to see this change. I do see that this will prevent the information in the file to always be available, and that is a negative. However, we do have the DBG file for developer oriented information that should be available at all times. Are anybody using the DBG file at this point?

**Comment by bska** [comment]
> Are anybody using the DBG file at this point?

I don't think so, at least not for anything quantitative.  I know I personally look at it only to get a vague idea of the underlying issue if something goes wrong.  The file suffers from information overload in my opinion and is hard to process with tools.  Even if we were to add some kind of message tag (e.g., `"INFOSTEP:"`) to simplify extracting certain pieces of information from the debug file, we would still need additional tooling&mdash;either personal scripts or something more official&mdash;to make that information useful for analysis purposes.

The INFOSTEP file here, and the new INFOITER file proposed in #4323, are mostly of interest to developers working on aspects of the linear and nonlinear solvers and in that context it's not unreasonable to rerun a case if we want additional forensic information.

**Comment by alfbr** [comment]
> > Are anybody using the DBG file at this point?
> 
> I don't think so, at least not for anything quantitative.

I am afraid that is correct, but could be some who do not capture the discussion here of course.

> I know I personally look at it only to get a vague idea of the underlying issue if something goes wrong.The file suffers >from information overload in my opinion and is hard to process with tools.

If that is indeed the case for all of us, I believe we should do something about it. One idea is to stop duplicating output in the PRT file, that alone would make it a lot less noisy.

**Comment by bska** [comment]
> > I know I personally look at it only to get a vague idea of the underlying issue if something goes wrong. The file suffers from information overload in my opinion and is hard to process with tools.
> 
> If that is indeed the case for all of us, I believe we should do something about it.

Possibly, but I think we'd need to do quite a bit of work on the structure of that file if it were to become useful as a machine readable information source.  Right now, it's pretty much readable to humans only.

> One idea is to stop duplicating output in the PRT file, that alone would make it a lot less noisy.

That would help in the sense that human readers would have to look at smaller amounts of text, but it wouldn't really help with the file's fundamental lack of structure.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> 1. Should we check the parameters and throw instead of silently assuming none if there typos?

Yeah, probably.  I've pushed an update to that effect.

> 2. Why is it steps and iteration (without s) for the enum? At least the help uses "s" everywhere.

I've switched to using plurals for both.  We accept the singular forms as aliases though.

**Comment by OPMUSER** [comment]
>     If that is indeed the case for all of us, I believe we should do something about it.

Yes, the debug file has become useless due to everybody writing their own debug information to the file, coupled with all the standard print reports being sent to the file. I would suggest that nothing is written to the debug file unless specifically requested, either via a command line option or a RPTDEBUG keyword, a new OPM Flow specific keyword. That way, we would not need the INFOSTEP and INFOITER files, as the developer could just output this information only to the debug file. 

> Possibly, but I think we'd need to do quite a bit of work on the structure of that file if it were to become useful as a machine readable information source. Right now, it's pretty much readable to humans only.

>     One idea is to stop duplicating output in the PRT file, that alone would make it a lot less noisy.

I have said many times that standard output should not go to the debug file.

> That would help in the sense that human readers would have to look at smaller amounts of text, but it wouldn't really help with the file's fundamental lack of structure.

I disagree here, one could always prefix each line that is required to be machine-readable with `INFOSTEP:`  or `INFOITER:` for example:

```
INFOITER: ReportStep    TimeStep        Time   Iteration      MB_Oil     CNV_Oil    MB_Water   CNV_Water      MB_Gas     CNV_Gas  WellStatus
INFOITER:         82           0  9.1200e+02           0  2.3284e-05  4.5422e-02  1.1767e-05  2.5912e+01  9.7662e-06  7.4694e-02        CONV
INFOITER:         82           0  9.1200e+02           1  2.9654e-07  3.8767e+00  2.1806e-07  4.1394e+00  5.2375e-08  2.9183e+01        CONV
INFOITER:         82           0  9.1200e+02           2  2.2179e-07  6.8047e-01  3.0610e-07  1.1331e+00  9.1907e-08  3.8215e+00        CONV
INFOITER:         82           0  9.1200e+02           3  7.9218e-08  2.1570e-01  1.0786e-07  9.9523e-01  3.6969e-08  2.5988e-01        CONV
INFOITER:         82           0  9.1200e+02           4  1.0330e-09  1.3516e+00  3.9736e-09  7.8332e-02  1.6815e-09  4.7527e-01        CONV

```
Thus, one only needs to parse lines beginning with `INFOITER:` etc. to enable machine readable input.
 
If the data is being written in real time, as opposed to being stored, then write it out to a temporary file and copy it back to the debug file at the end of simulation. We do something like this for the RSM file, when at the end of the run we process the summary files and write out the RSM file. So why cannot we do the same for this type of output? But there again, there is always grep and regular expressions to extract the information if it is written to the debug file in real time.

Note the INFOITER  information is useful for users as well, not just for developers, since it may help in resolving numerical issues.

Concerning this particular "report", we have a` WellStatus` column, which I assume is for the well equations. Is it possible to have  a similar one for the grid cells? Also it would be nice to identify time step chops TCHOP, as well REPT, HALF, DIFF, THRP, MINS, etc.

File: opm/simulators/flow/ConvergenceOutputConfiguration.cpp [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+        auto u = std::unique(unsupp.begin(), unsupp.end());
+
+        const auto pl = (unsupp.size() != 1) ? "s" : "";
+
+        throw std::invalid_argument {
+            fmt::format("Unsupported convergence output "
+                        "option value{}: {}\n"
+                        "Supported values are \"none\", "
+                        "\"steps\", and \"iterations\"", pl,
+                        fmt::join(unsupp.begin(), u, ", "))
```
Comment (blattms) [inline opm/simulators/flow/ConvergenceOutputConfiguration.cpp:58]: I think we should also print what command line parameter we are talking about. Otherwise users are lost.

File: opm/simulators/flow/ConvergenceOutputConfiguration.cpp [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+            if (auto option = values.find(value); option != values.end()) {
+                opt.push_back(option->second);
+            }
+            else {
+                unsupp.push_back(value);
+            }
+        }
+
+        if (! unsupp.empty()) {
+            reportUnsupportedOptionValuesAndThrow(std::move(unsupp));
```
Comment (blattms) [inline opm/simulators/flow/ConvergenceOutputConfiguration.cpp:88]: Do you use some kind of guideline on when to use move and when not? What exactly will it buy you here?

Seems like this code is not performance critical and one code rely on inlining. It seems less readable at least,

File: opm/simulators/flow/ConvergenceOutputConfiguration.cpp (hunk 1 above)
Comment (bska) [reply opm/simulators/flow/ConvergenceOutputConfiguration.cpp]: > I think we should also print what command line parameter we are talking about. Otherwise users are lost.

I've pushed an update to that effect.

File: opm/simulators/flow/ConvergenceOutputConfiguration.cpp (hunk 2 above)
Comment (bska) [reply opm/simulators/flow/ConvergenceOutputConfiguration.cpp]: > Do you use some kind of guideline on when to use move and when not?

Yes.  I write `std::move()` when at least one of the following two conditions is satisfied

1. When I have to, e.g., because the function being called takes a value of a non-copyable type (e.g., a `std::unique_ptr<>`) or when the function being called takes an r-value and I only have an object
2. When `std::move()` expresses the desired semantics, usually "I'm transferring ownership because I don't need it anymore."  While `std:move()` is **primarily** an optimisation of copy, that's not **all** that it does.

> What exactly will it buy you here?

In this case it expresses the "I'm transferring ownership of this object to the other function because I don't need it anymore."  The function being called needs a separate vector object because it's going to manipulate it in order to do its job and I have one of those objects at the call site.  For what it's worth, we do the same in [`Summary.cpp`](https://github.com/OPM/opm-common/blob/9d4b36a891834e537881e788d731251002fc2776/src/opm/output/eclipse/Summary.cpp#L4095-L4096), and for the exact same reason.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]
Looks good now.

I would merge, but not 1000% sure whether this is the final state. Hence leaving this to you.

**Comment by bska** [comment]
> Looks good now.

Thanks.

> not 1000% sure whether this is the final state.

Understood.  The current state is as far as I intended to take this right now, because it meets the requirements of #3710 and #4323.  If additional requirements arise in the future then we may consider expanding the capabilities of this class.

I'll merge this now.
