### PR TITLE
Fixes the parallel Euclidian product for multiple phases.

### LINKED ISSUE #713: Wrong ordering of `SimulationDataContainer::saturation()` assumed in euclidianNormSquared
According to @atgeirr:  All saturations of the first cell before the saturations of the next one
But [euclidianNormSquared](https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#L1127-L1152) assumes the opposite (all staturations of the first phase come before the next one).
This will lead to wrong results [here](https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#L1653), and [here](https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#L1659).

### PR DESCRIPTION
**Pull request by blattms**
This is used to compute the Euclidian product for the saturations.
Thes are ordered in an interleaved manner (all saturations for cell
with index 0, the all for index 1, ...). Up to now the implementation
assumed a different ordering: blockwise (all saturations for phase 0 first,
then all saturations phase 1, ...).
With this commit the computation uses the right assumption.

Closes #713

### CODE REVIEW

File: opm/autodiff/BlackoilModelBase_impl.hpp [hunk 1]
```diff
@@ -1135,19 +1139,39 @@ namespace detail {
...
-                        boost::make_iterator_range(it + i * size_per_component,
-                                                   it + (i + 1) * size_per_component);
+                        boost::make_iterator_range(it, end);
                     info.computeReduction(component_container,
                                            Opm::Reduction::makeInnerProductFunctor<double>(),
-                                           component_product);
+                                           product);
+                }
+                else
+                {
```
Comment (atgeirr) [inline opm/autodiff/BlackoilModelBase_impl.hpp]: In this branch, I don't understand how you avoid using computeReduction() and still get a correct result in parallel?

Comment (atgeirr) [inline opm/autodiff/BlackoilModelBase_impl.hpp]: Question still stands.

Comment (blattms) [inline opm/autodiff/BlackoilModelBase_impl.hpp]: Great catch! After comprehending your question, I don't understand that either. There is a reduction missing. Will fix it.

**Comment by blattms** [comment]
I added the missing reduction.

**Comment by atgeirr** [comment]
This looks correct now, and will merge it once Travis is done.
