### PR TITLE
not adding wells without perforations to WellsManager

### LINKED ISSUE #1687: Segfault example
Consider the 2 attached decks.  The only difference between them is a the location of the connection of the injector.  VER.DATA fails with a segmentation fault and VER_OK.DATA runs successfully.  I did the tests with the docker image openporousmedia/opmreleases:nightly-2018-11-30
[decks.zip](https://github.com/OPM/opm-simulators/files/2703965/decks.zip)

### PR DESCRIPTION
**Pull request by GitPaean**
this closes #1692 and trying to fix  #1687 . 

It turned out not trivial to decide where is the best place to do this. And also, I could not see any messages from `OPM_MESSAGES`.

### CODE REVIEW

File: opm/core/wells/WellsManager_impl.hpp [hunk 1]
```diff
@@ -199,6 +199,13 @@ void WellsManager::createWellsFromSpecs(std::vector<const Well*>& wells, size_t
                 }
             }
         }
+
+        if (wellperf_data[active_well_index].empty()) {
+            OPM_MESSAGE("****Warning: there is no perforations associated with the well "
+                        << well->name() << ", the well is ignored");
```
Comment (atgeirr) [inline opm/core/wells/WellsManager_impl.hpp]: We should rather use OpmLog::warning() for this. The OPM_MESSAGE macro should be deprecated I think.

**Comment by GitPaean** [comment]
With https://github.com/OPM/ewoms/pull/283,  the following situation should never happen.  Maybe we should change it to be a safety check instead of an action of ignoring.  

```
                    const int* cpgdim = cart_dims;
                    int cart_grid_indx = i + cpgdim[0]*(j + cpgdim[1]*k);
                    std::map<int, int>::const_iterator cgit = cartesian_to_compressed.find(cart_grid_indx);
                    if (cgit == cartesian_to_compressed.end()) {
                        OPM_MESSAGE("****Warning: Cell with i,j,k indices " << i << ' ' << j << ' '
                                    << k << " not found in grid. The completion will be igored (well = "
                                    << well->name() << ')');
                    }
```

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Given that Eclipse according to the discussion in #1687 seems to not remove cells at identical locations, it is not necessarily a gootant to support. We should therefore make a test case for this which just uses ACTNUM to deactivate the well cells instead.

**Comment by GitPaean** [comment]
I will add the unit test.  Currently the removal of connection happens in ebos, which causes small problem in creating in unit test. I will try to make an alternative.

**Comment by GitPaean** [comment]
Very weirdly, this PR can catch the problem from `VER.DATA`, while it could not catch the problem setup with `ACTNUM`.

**Comment by GitPaean** [comment]
The `ACTNUM` is taken care of in the parser. If a `Well` does not have connection due to `ACTNUM` setup, the well will be shut. 

As a result, the case reported in https://github.com/OPM/opm-simulators/issues/1687 is unique in some sense. It is most likely more similar to the situation that a grid cell is removed due to PINCH. 

If all the connections are disabled by `ACTNUM`, the parser will know and also the output side will also know it and throw a message as follows, 
```
ERROR: Uncaught std::exception when running tasklet: No completions defined for well: INJE01. Can not infer reference depth. Trying to continue
```
As reported in https://github.com/OPM/opm-simulators/issues/1687, the grid processing is different between flow and ECL, which makes this PR more like a safety check to avoid `invalid memory read`.  

This PR does not introduce anything bad. 

Anyway, please suggest how we should proceed for the unit test here. @bska @atgeirr

**Comment by bska** [comment]
> the grid processing is different between flow and ECL

Probably yes.  Flow normalises all its grid data through [`EclipseGrid`]() and extracts a corner-point geometry description (i.e., a `COORD`/`ZCORN` pair) from its [`export*` member functions]().  Therefore Flow will, as a byproduct, run cell deactivation as a result of pinch-outs.  On the other hand ECLIPSE's block centred geometry (`D{X,Y,Z}` and `TOPS`) appears to not really care about an individual cell's relative locations with respect to other cells and may therefore accept a geometry in which more than one cell occupies the same location in physical space.  At best that would be roundabout&mdash;possibly sneaky&mdash;way of turning off effects of gravity.  It would be interesting to see what ECLIPSE reports for the physical location&mdash;at least the depth&mdash;of each cell's centre point in the `TOPS = 100*1000` case.

> As a result, the case reported in #1687 is unique in some sense. It is most likely more similar to the situation that a grid cell is removed due to PINCH.

Yes, that's exactly what happens in Flow's case.

**Comment by atgeirr** [comment]
I see no clear way to build a good test case for this, so I propose we either
 -  merge as is, or
 - use the VER.DATA case, and keep in mind that it will become a useless or wrong test if we change the behaviour for degenerate TOPS.

I'm ok with either. @bska?

**Comment by bska** [comment]
> I see no clear way to build a good test case for this,

I do.  Make a 5-by-1-by-2 case described in corner-point geometry format, put the producer in (5,1,1) and the injector in (1,1,2) and pinch that cell manually through `ZCORN`.

**Comment by GitPaean** [comment]
> I do. Make a 5-by-1-by-2 case described in corner-point geometry format, put the producer in (5,1,1) and the injector in (1,1,2) and pinch that cell manually through ZCORN.

Sure. Let me give a shoot. I never worked with ZCORN and COORD, and it should be doable for a simple case. thanks for the suggestion.

**Comment by GitPaean** [comment]
> I do. Make a 5-by-1-by-2 case described in corner-point geometry format, put the producer in (5,1,1) and the injector in (1,1,2) and pinch that cell manually through ZCORN.

Basically it is the same with the case from `VER.DATA`, right?

**Comment by OPMUSER** [comment]
Just a brief comment. Rather than use ACTNUM for the criteria it should be PORV, that is if the PORV is zero then the cell is inactive. This means if ACTNUN for a cell is 1 but PORV (RV, NTG, PORV etc., equals zero) then cell is inactive.

I re-ran the example cases with more output so I can see the model's in 3D, they all look the same. Except the ECL 100 model runs but the Flow version crashes. From an engineering point of view I would not trust the results as I do not know what is going on. How can you complete in layer two when there is no layer two.

However, I'm happy to go whatever you guys decide, as I think the input is the error not the simulator.

**Comment by GitPaean** [comment]
> I re-ran the example cases with more output so I can see the model's in 3D, they all look the same. Except the ECL 100 model runs but the Flow version crashes. From an engineering point of view I would not trust the results as I do not know what is going on. How can you complete in layer two when there is no layer two.

Can you share a little more information here? With `VER.DATA` (`TOPS
    100*1000
  /`), Eclipse also disabled the bottom 4 layers? which means only the 10 cells at the above layers are active. 

In OPM, the 90 cells in the bottom 9 layers are de-activated.

**Comment by GitPaean** [comment]
> I do. Make a 5-by-1-by-2 case described in corner-point geometry format, put the producer in (5,1,1) and the injector in (1,1,2) and pinch that cell manually through ZCORN.

Pinching cell through ZCORN will be aware of by parser. The connection will not be added in the parser.

**Comment by GitPaean** [comment]
> Just a brief comment. Rather than use ACTNUM for the criteria it should be PORV, that is if the PORV is zero then the cell is inactive. This means if ACTNUN for a cell is 1 but PORV (RV, NTG, PORV etc., equals zero) then cell is inactive.

PORV does de-active the cell, while it is done in the parser side, will not make the current PR take effects.

**Comment by GitPaean** [comment]
I might provide some misleading information, because some inconsistency happens here. I will update when I figure out the problem.

**Comment by bska** [comment]
> > I do. Make a 5-by-1-by-2 case described in corner-point geometry format, put the producer in (5,1,1) and the injector in (1,1,2) and pinch that cell manually through `ZCORN`.
> 
> Pinching cell through `ZCORN` will be aware of by parser.

Ah, right&mdash;the parser calculates pore-volumes and deactivates cells if the pore-volumes are zero.  In that case we'll need to somehow convince the parser that the cells have a positive pore-volume and nevertheless get a zero volume from the grid processing.  We might just have to use the original `VER.DATA` to achieve that effect.

**Comment by GitPaean** [comment]
Sorry for the misleading information. Looks like using `PINCH` keyword can help to make it works.

**Comment by GitPaean** [comment]
> We might just have to use the original VER.DATA to achieve that effect.

`VER.DATA` kind of creates a not well-defined situation. If we want to fix that case or follow what ECL does, it is something more difficult than what this PR support. 

The unit test is added based on `PINCH` keyword. The pinchout action happens after parsing.

**Comment by GitPaean** [comment]
jenkins build this please

File: tests/test_wellsmanager.cpp [hunk 2]
```diff
@@ -306,3 +306,25 @@ BOOST_AUTO_TEST_CASE(WellSTOPOK) {
...
+    Opm::EclipseState eclipseState(deck);
+    Opm::GridManager gridManager(eclipseState.getInputGrid());
+    const auto& inputGrid = eclipseState.getInputGrid();
+    const Opm::TableManager table ( deck );
+    const Opm::Eclipse3DProperties eclipseProperties ( deck , table, inputGrid);
+    const Opm::Runspec runspec (deck);
+    Opm::Schedule sched(deck, inputGrid, eclipseProperties, runspec);
+
+    const auto eclipseGrid = Opm::UgGridHelpers::createEclipseGrid(*gridManager.c_grid(), inputGrid);
+    sched.filterConnections(eclipseGrid);
```
Comment (bska) [inline tests/test_wellsmanager.cpp]: Doesn't this simply remove the connection from the `Schedule` object?  In that case we're not actually testing the new code at all.

Comment (GitPaean) [reply tests/test_wellsmanager.cpp]: Yes, but it will not change the status of the well to be `SHUT`. A well is `OPEN`, but have no connection due to the grid processing after parsing, which is exactly what we are testing here. 

If the connections are removed during the parsing period, the well be set to be `SHUT`.

Comment (GitPaean) [reply tests/test_wellsmanager.cpp]: Or you can argue that in `filterConnections()`, we should set well to be `SHUT` if there is no connection left.  It is also something we can do.

Comment (GitPaean) [reply tests/test_wellsmanager.cpp]: If we do this, then we will throw in `WellsManager_impl.hpp` in stead of giving a warning.

**Comment by atgeirr** [comment]
Since there is a test now, and all is green, I'll merge. Thanks!

**Comment by OPMUSER** [comment]
@GitPaean all four models look like this:
2019-01-11 12_39_36-ubuntu-mate-18 04 3 tls opm 2018-10 running - oracle vm virtualbox

**Comment by GitPaean** [comment]
@OPMUSER , thanks. 

The only explanation I have is that ECL did not remove the olverlapped cells. Although we see there are 10 cells visually, ECL treats them as 100 cells and getting the connection relation based on a Cartesian indices without considering their actual relative locations.

**Comment by OPMUSER** [comment]
Well I would say rubbish in gives you rubbish out. This is an input error, but ECL still runs, so I would call this a bug in ECL. Flow should just gracefully terminate.

**Comment by GitPaean** [comment]
> Well I would say rubbish in gives you rubbish out. This is an input error, but ECL still runs, so I would call this a bug in ECL. Flow should just gracefully terminate.

:+1: 

I would not say `gracefully`, but I will not say it is good to finish running without giving any WARNING about the setup either.

**Comment by OPMUSER** [comment]
By gracefully I mean no SegFault
