### PR TITLE
Call writeInit with global grid and properties.

### LINKED ISSUE #765: OutputWriter::writeInit cannot work correctly in parallel.
`SimulatorBase::run` starts of by writing the init file with the output writer, see [here](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/SimulatorBase_impl.hpp#L116). The eclipse writer in [BlackoilOutputWriter::writeInit](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp#L253) assumes that both the NNC and the vector of properties returned by the [`simProps()`](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/GeoProps.hpp#L242-L284) function contains correct information of the whole domain.  Unfortunately, as of now the vector with the properties will have the correct size (global size), but all  cells not represented on the current process will have transmissibility zero set for all global cells not represented, unconditionally. This is due to the `grid_` only representing the only local excerpt of the global grid. In addition each process will write to the same file which might cause additional problems.
Assuming that this information is only written once at the very beginning of a simulation, the easiest fix would be to move the writing into FlowMain.hpp before the call to [`distributeData()`](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/FlowMain.hpp#L148). Can anyone confirm this assumption?

### PR DESCRIPTION
**Pull request by blattms**
Previously, the call was made after the grid was distributed.
This means that each process wrote it, but only with his cells
active which was just a part of the whole domain.

With this PR we make the writeInit call before distributing the
grid and make sure that only one process calls it.

Closes #765.

### CODE REVIEW

**Comment by blattms** [comment]
With the vacation season coming to end would anybody care to take a look at this PR?

It should not change a thing for sequential flow but might prevent false data in the output for parallel runs.

File: opm/autodiff/SimulatorBase_impl.hpp [hunk 1]
```diff
@@ -111,10 +111,6 @@ namespace Opm
             adaptiveTimeStepping.reset( new AdaptiveTimeStepping( param_, terminal_output_ ) );
         }
 
-
-
-        output_writer_.writeInit( geo_.simProps(grid_) , geo_.nonCartesianConnections( ) );
```
Comment (atgeirr) [inline opm/autodiff/SimulatorBase_impl.hpp]: Looks like you also discovered an extra call: looks to me like we currently always write init twice!

**Comment by atgeirr** [comment]
This looks fine, will merge.

**Comment by blattms** [comment]
Great! Thanks!
